name: Docker Build and Push

on:
  push:
    tags:
      - v*

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Log into ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: musecr.azurecr.cn
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image for Next.js app
        uses: docker/build-push-action@v4
        timeout-minutes: 10  # 10 分钟超时
        with:
          context: .
          push: true
          build-args: |
            NEXT_SERVER_ACTIONS_ENCRYPTION_KEY=${{ secrets.NEXT_SERVER_ACTIONS_ENCRYPTION_KEY }}
          tags: |
            ghcr.io/bmrlab/atypica-llm-app:${{ env.VERSION }}
            ghcr.io/bmrlab/atypica-llm-app:latest
            musecr.azurecr.cn/bmrlab/atypica-llm-app:${{ env.VERSION }}
            musecr.azurecr.cn/bmrlab/atypica-llm-app:latest

      - name: Build and push Docker image for Jobs
        uses: docker/build-push-action@v4
        timeout-minutes: 10  # 10 分钟超时
        with:
          context: .
          file: ./Dockerfile.job
          push: true
          tags: |
            ghcr.io/bmrlab/atypica-llm-app:${{ env.VERSION }}-job
            ghcr.io/bmrlab/atypica-llm-app:latest-job
            musecr.azurecr.cn/bmrlab/atypica-llm-app:${{ env.VERSION }}-job
            musecr.azurecr.cn/bmrlab/atypica-llm-app:latest-job

      - name: Setup Kubernetes Config And Update Deployment
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_MUSE_CLUSTER }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          kubectl config use-context muse-aws-cn-prod
          kubectl set image deployment/atypica-llm-app atypica-llm-app=musecr.azurecr.cn/bmrlab/atypica-llm-app:${{ env.VERSION }} --namespace bmrlab
